<a href="https://colab.research.google.com/github/AnantaJoy/tensorflow_essentials/blob/main/tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [4]:
mat1 = tf.constant([[1.,2.]])
type(mat1)

tensorflow.python.framework.ops.EagerTensor

In [5]:
print(mat1)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)


In [7]:
mat2 = tf.constant([[2],
                   [6]])
type(mat2)

tensorflow.python.framework.ops.EagerTensor

In [8]:
print(mat2)

tf.Tensor(
[[2]
 [6]], shape=(2, 1), dtype=int32)


In [9]:
mat3 = tf.constant([ [[2,5],
                     [2,6]],
                    [[5,7],
                     [5,8]] ])

In [10]:
print(mat3)

tf.Tensor(
[[[2 5]
  [2 6]]

 [[5 7]
  [5 8]]], shape=(2, 2, 2), dtype=int32)


In [19]:
zeros = tf.zeros([2,2])
print(zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


In [21]:
ones = tf.ones([100,100])*0.5
ones

<tf.Tensor: shape=(100, 100), dtype=float32, numpy=
array([[0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       ...,
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, ..., 0.5, 0.5, 0.5]], dtype=float32)>

In [23]:
mat_x = tf.constant([[2,4]])
negOf_mat_x = tf.negative(mat_x)
print(negOf_mat_x)

tf.Tensor([[-2 -4]], shape=(1, 2), dtype=int32)


## Tensor Mathematical Operation

In [24]:
mat_x = tf.constant([[1,2,3],
                     [2,4,6]])
mat_y = tf.constant([[1,5,7],
                     [2,6,8]])
tf.add(mat_x,mat_y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  7, 10],
       [ 4, 10, 14]], dtype=int32)>

In [27]:
tf.subtract(mat_x,mat_y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0, -3, -4],
       [ 0, -2, -2]], dtype=int32)>

In [28]:
tf.multiply(mat_x,mat_y)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1, 10, 21],
       [ 4, 24, 48]], dtype=int32)>

In [29]:
tf.pow(mat_x,mat_y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[      1,      32,    2187],
       [      4,    4096, 1679616]], dtype=int32)>

In [35]:
tf.divide(mat_x,mat_y)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.        , 0.4       , 0.42857143],
       [1.        , 0.66666667, 0.75      ]])>

In [36]:
tf.truediv(mat_x,mat_y)

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1.        , 0.4       , 0.42857143],
       [1.        , 0.66666667, 0.75      ]])>

**Gaussian Distribution**

In [ ]:
# from math import pi
# mean = 0
# sigma = 1
# x = tf.constant([[1,2]])
# (tf.exp(tf.negative(tf.pow(x - mean, 2)/
#                     (2 * tf.pow(sigma, 2) ))) *
#  (1 / (sigma * tf.sqrt(2 * pi) )))

In [52]:
x = tf.constant([[1.,2.]])
neg_x = tf.negative(x)
with tf.compat.v1.Session() as sess:
  hello = tf.constant('Hello')
  result = sess.run(hello)

print(result)

b'Hello'


In [54]:
sess=tf.compat.v1.InteractiveSession()
x = tf.constant([[1,3],[5,7]])
result = x.eval()

NotImplementedError: ignored